---
title: "Exercise 27-11"
author: "Lais Silva Almeida Zanchetta, Daniel Ferreira Zanchetta"
date: "11/27/2019"
output: word_document
---

### 1)	Enumere cuales son los elementos clave de una prueba de hipótesis y su significado.
 Resp.: En primer lugar, siguiendo el principio de Karl Popper, una hipotesis solo puede ser entendida como cientifica si puede ser falsificable. Teniendo esto en cuenta, los elementos claves de una prueba de hipótesis son:
        - Null hypothesis: la hipótesis nula és la hipótesis contraria a que nos gustaría probar (que es la llamada alternative hypothesis).
        - Alternative hypothesis: es la hipotesis que se quiere probar. Es decir, és una variación de la hipotésis nula que se desea validar.
        - Test Statistic: es un valor estadístico adecuado para comparar la hipótesis nula con la hipótesis alternativa (variable aleatória)
        - Reference distribution: prueba estadística de la hipótesis nula, si la hipótesis nula és verdadera
        - p_value: Probabilidad estadística de la prueba observada. Si el p_value es muy bajo la hipótesis nula és rechazada (hasta los dias de hoy es considerada rechazada si el p_value < 0,05)

### 2)	Un elemento clave en toda prueba de hipótesis es la distribución de referencia del estadístico de la prueba. Diga de que maneras podemos conocer (o aproximar) la distribución de referencia para la prueba de hipótesis de querer ver si una media de una muestra es igual o no a un cierto valor nominal. Especifique como obtendría o cual sería esta distribución de referencia.
Resp.: Podemos conocer la distribución de referencia a través de (1) datos historicos, y tambien a través de (2) sin datos historicos. 
Para (1) obtendría una amuestra y calcularía su media. En seguida, calcularía cuantas amuestras son mas pequeñas o iguales al valor clave de la hipotesis.
Para (2), se hace necesario crear una distribución de referencia haciendo suposición y utilizando la teoria. Tambien es calculada la media de la amuestra. En seguida debemos verificar la media de la amuestra en la distribución de referencia, y cuanto sería su p-value.

### 3) Un amigo me ofrece un piso por valor de 8MPts. Dejando de lado todos los otros factores intervinientes en la decisión de compra de un piso y solo teniendo en cuenta su precio, puedo considerar que se trata de ocasión para comprar?. Que suposiciones necesito hacer para resolver el problema. (Para resolver esta pregunta utilice los datos disponibles que crea conveniente).
Resp.: No se puede afirmar si se trata de ocasión para comprar. Es necesario considerar, al menos, tener una ditribución de referencia de los precios promedio de los pisos de donde el piso esta localizado, y tambien considerar con qué quieres hacer la comparación (por ejemplo, si quieres considerar otros pisos de la misma zona y entre zonas/comunidades distintas). Además de esto, tambien pueden ser necesarios mas detalles sobre el piso en si, como por ejemplo la cantidad de habitaciones, planta, garaje, etc...

### 4.	Sabemos que la media de los precios de los pisos (de 3 habitaciones) en l’Eixample es de 16.81 y su desviación tipo es de 5.91. Suponiendo que la muestra obtenida en el ejercicio 1 (7.80, 12.60, 15.96, 13.50, 8.25, 31.29, 16.46) es aleatoria. ¿Podemos asegurar de que se trata de una muestra de pisos de l’Eixample?
Resp.: Con el resultado obtenido de 70,31% se acepta la hipotesis nula, entonces en este caso no se puede afirmar que se trata de una muestra de pisos de l'Eixample.
```{r}
x1 <- c(7.80, 12.60, 15.96, 13.50, 8.25, 31.29, 16.46)

mu0 <- 16.81
sigma <- 5.916

m<-mean(x1)
n<-length(x1)

std<-sd(x1)/sqrt(n)

t<-(mu0 - m)/std
pt(t,df=n-1)
```

### 5.	El siguiente año, los precios de una muestra aleatoria de pisos de 3hab. en l’Eixample han sido 13.57 14.80 22.36 29.29 22.70. Puedo afirmar de que no ha habido cambio de precio entre los dos años?

### 6.	Calcula el p_valor en para la misma prueba del problema anterior, usando el método de permutaciones.
